### ISSUE TITLE
[Seeking advice] Embedding and decoding+playing a large Codec2 blob

### ISSUE THREAD

**Issue by pilaf** [rameshvarun/codec2-emscripten#1]
Hi. First of all apologies since this isn't a real issue, feel free to close/ignore.

Just for fun I'm using Codec2 to fit a podcast episode in a floppy disk. Practicality isn't a big priority, but the disk has to include _some_ method of playing the Codec2-encoded audio, for which the simplest option is a text file with instructions on how to convert Codec2 to WAV, but if I could somehow include software that plays the audio that would be so much nicer.

I found your project and figured that it'd be the best chance I have of building a platform-agnostic player that I could just include in the floppy, however I'd have to:

1) modify it to read the raw Codec2 blob instead of a Base64
2) make sure the decoder/player can handle a roughly 1h40m-long audio

So before I spend much time attempting that myself I thought to ask whether you think this is feasible, or if I should give up before trying. Any advice would be greatly appreciated.

Thank you, and cool project by the way!

**Comment by rameshvarun** [comment]
If you want to create a binary blob instead of base64, you can decode the base64 to a file. I can also add direct blob download to this demo as well.

```bash
echo "dOmBUOG..." | base64 --decode > output.codec2
```

As far as I'm aware, the blobs should be compatible with any codec2 decoder, however you have to set the same codec mode (default is 700C).

As for fitting cross-platform decoding software onto the disk itself, you could try one of the following:
- Create a webpage similar to this demo that can run entirely from "file://" urls and place that on the disk. This demo is already pretty big, so it will probably be a challenge to fit it on a floppy disk, but maybe possible.
- Alternatively compile `c2dec` from the [upstream codec2 project](https://github.com/drowe67/codec2) using [cosmopolitan](https://github.com/jart/cosmopolitan), which creates an .exe that can run on macOS, Windows, and Linux. You would still need to play the audio (not sure how to do that in a cross-platform way).

**Comment by rameshvarun** [comment]
If you go with the "file://" url webpage approach, here's a couple things you can try.

- Get rid of c2enc.js/wasm - you don't need it since you only need the decoder.
- Get rid of sox.js/wasm - sox is simply used to convert the codec2 PCM to a wav so it can play in the `<audio>` element. It can probably done in a simpler way.
- Pre-compress c2dec.js/wasm with gzip and use [DecompressionStream](https://developer.mozilla.org/en-US/docs/Web/API/DecompressionStream#examples) to decompress and load them.

**Comment by pilaf** [comment]
Hey, thanks for taking the time to reply.

> I can also add direct blob download to this demo as well.

Please don't worry about that, I already have the Codec2-encoded audio blobs, I'm only looking at providing a user-friendly way to play them :)

Your suggestions are more or less what I had in mind, so you kinda confirmed my plan. Not sure if I'll be able to pull it off, but I'll give it a shot.

The cosmopolitan suggestion is very interesting too, I wasn't aware of it, so I'll give it a look. Thanks!

**Comment by pilaf** [comment]
@rameshvarun I managed to make it work and be small enough to fit in the floppy disk (460KB gzipped) 🥳 

I still have one challenge to deal with, which is that the `file://` protocol doesn't allow me to load the .wasm file due to CORS. I guess I could try to base64-encoded it and inline it using a `data:` URI, but that would most likely bloat the end result and make it not fit in the disk any more, or I could have the user load the .wasm through an `<input>`, but that's very clunky.

Anyway, I'll figure it out, but I wanted to update you on the progress and thank you again for your help and for creating this lovely project in the first place.

**Comment by pilaf** [comment]
I ended up inlining the .wasm with a `data:` URI and that did the trick. It bloats the final size a bit, but after compression it's not so bad.

I'll credit you in the floppy disk's README, by the way.

**Comment by rameshvarun** [comment]
Glad to hear that it worked out - thanks for sharing!
